version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:admin123@db:5432/question_answer
    depends_on:
      - db

  db:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: question_answer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123

  migrate:
    build: .
    command: flask db upgrade
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:admin123@db:5432/question_answer

  test:
    build: .
    command: pytest test.py
    depends_on:
      - db
      - migrate
    env_file:
      - .env
    environment:
      - FLASK_ENV=testing
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:admin123@db:5432/question_answer
