"""Initial migration

Revision ID: 38881fef834f
Revises: 
Create Date: 2024-07-13 20:29:47.368152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38881fef834f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('q_aentity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('q_aentity')
    # ### end Alembic commands ###
